version: '3.7'


services:
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
  web:
    build: 
      context: .
    command: >
      sh -c "./entrypoint.sh"
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

volumes:
  postgres_data:
