services:

  web:
    build:
      context: .
    container_name: web-app
    command: /bin/bash "/app/entrypoint.sh"
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    
  db:
    image: postgres:latest
    container_name: db-app
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
